# ==========================================
# |    RaidsPerRegion4 by ShermansWorld    |
# ==========================================

# Update Checker Settings
update-checker:
  enable: true
  console: true # Post message to console
  op: true # Send update notification to opped players on join

GlobalRaidSettings:
  PreventVanillaMobsSpawningInRaids: true
  ForceMobSpawningInRegionOnRaidStart: true
  KeepInventoryOnPlayerDeath: false
  KeepEXPOnPlayerDeath: false
  DisablePvPInRaids: false
  ClearMobsOnRaidLoss: false
  ShowPlayerDeathMessagesInRaids: true

RaidPresets:
  Skeletal:
    default: false
    boss:
    mobs:
      SkeletalMinion:
        mobLevel: 1.0
        chance: 0.60
        weight: 1
      SkeletalKnight:
        mobLevel: 1.0
        chance: 0.15
        weight: 3
      SkeletalKing:
        mobLevel: 1.0
        chance: 0.05
        weight: 4
  Everything:
    default: true
    boss: AngrySludge
    mobs:
      SkeletalMinion:
        mobLevel: 1.0
        chance: 0.60
        weight: 1
      StaticallyChargedSheep:
        chance: 0.35
        weight: 2
        mobLevel: 1.0
      SkeletalKnight:
        mobLevel: 1.0
        chance: 0.15
        weight: 3
      SkeletalKing:
        mobLevel: 1.0
        chance: 0.05
        weight: 4

RaidTiers:
  1:
    default: true
    maxMobsAtOnce: 100
    killsGoal: 100
    timeLimit: 600
    mobSpawnsPerCycle: 2
    cycleRate: 1.0
  2:
    default: false
    maxMobsAtOnce: 100
    killsGoal: 100
    timeLimit: 600
    mobSpawnsPerCycle: 2
    cycleRate: 1.0
  3:
    default: false
    maxMobsAtOnce: 100
    killsGoal: 100
    timeLimit: 600
    mobSpawnsPerCycle: 2
    cycleRate: 1.0

TitleMessages:
  enabled: true
  raidStartTitle: "<dark_red><bold>Tier <raid_tier> Raid Inbound"
  raidStartSubtitle: "<gold>Prepare to fight!"
  raidWinTitle: "<dark_green><bold>Raid Won!"
  raidWinSubtitle: "<gold>The raiders have fled"
  raidLoseTitle: "<dark_red><bold>Raid Lost!"
  raidLoseSubtitle: "<gold>This can't be good..."
  raidCancelTitle: "<aqua><bold>Raid Cancelled"
  raidCancelSubtitle: "<gold>Raid Cancelled by <raid_starter>"
  raidBossSpawnTitle: "<red><bold>Raid Boss Spawned"
  raidBossSpawnSubtitle: "<gold>Kill <boss_name> to win the raid!"

RaidResultConsoleCommands:
  enabled: true
  raidWinCommands:
    global:
      - "broadcast The tier <raid_tier> raid on <raid_area_name> has been won!"
    perParticipant:
      - "eco give <raid_participant_name> 100"
      - "msg <raid_participant_name> nice job!"
  raidLossCommands:
    global:
      - "broadcast The tier <raid_tier> raid on <raid_area_name> has been lost!"
    perParticipant:
      - "eco take <raid_participant_name> 50"