# ==========================================
# |    RaidsPerRegion4 by ShermansWorld    |
# ==========================================

# Update Checker Settings
update-checker:
  enable: true
  console: true # Post message to console
  op: true # Send update notification to opped players on join

# Translation, specify the language file to use, for example `en-US` which will load `/translations/en-US.yml`
translation: "en-US"

GlobalRaidSettings:
  PreventVanillaMobsSpawningInRaids: true
  ForceMobSpawningInRegionOnRaidStart: true
  KeepInventoryOnPlayerDeath: false
  KeepEXPOnPlayerDeath: false
  DisablePvPInRaids: false
  ClearMobsOnRaidLoss: false

RaidPresets:
  Skeletal:
    default: false
    boss:
    mobs:
      SkeletalMinion:
        mobLevel: 1.0
        chance: 0.60
        weight: 1
      SkeletalKnight:
        mobLevel: 1.0
        chance: 0.15
        weight: 3
      SkeletalKing:
        mobLevel: 1.0
        chance: 0.05
        weight: 4
  Everything:
    default: true
    boss: AngrySludge
    mobs:
      SkeletalMinion:
        mobLevel: 1.0
        chance: 0.60
        weight: 1
      StaticallyChargedSheep:
        chance: 0.35
        weight: 2
        mobLevel: 1.0
      SkeletalKnight:
        mobLevel: 1.0
        chance: 0.15
        weight: 3
      SkeletalKing:
        mobLevel: 1.0
        chance: 0.05
        weight: 4

RaidTiers:
  1:
    default: true
    maxMobsAtOnce: 100
    killsGoal: 100
    timeLimit: 600
    mobSpawnsPerCycle: 2
    cycleRate: 1.0
  2:
    default: false
    maxMobsAtOnce: 100
    killsGoal: 100
    timeLimit: 600
    mobSpawnsPerCycle: 2
    cycleRate: 1.0
  3:
    default: false
    maxMobsAtOnce: 100
    killsGoal: 100
    timeLimit: 600
    mobSpawnsPerCycle: 2
    cycleRate: 1.0

TitleMessages:
  enabled: true
  RaidStartTitle: "&4&lTier @TIER Raid Inbound"
  RaidStartSubtitle: "&6Prepare to fight!"
  RaidWinTitle: "&2&lRaid Won!"
  RaidWinSubtitle: "&6The raiders have fled"
  RaidLoseTitle: "&4&lRaid Lost!"
  RaidLoseSubtitle: "&6This can't be good..."
  RaidCancelTitle: "&b&lRaid Cancelled"
  RaidCancelSubtitle: "&6Raid Cancelled by @OWNER"
  RaidBossSpawnTitle: "&c&lRaid Boss Spawned"
  RaidBossSpawnSubtitle: "&6Kill @BOSS to win the raid!"

RaidResultConsoleCommands:
  enabled: true
  raidWinCommands:
    global:
      - "broadcast The tier @TIER raid on @NAME has been won!"
    perParticipant:
      - "eco give @PLAYER 100"
      - "msg @PLAYER nice job!"
  raidLossCommands:
    global:
      - "broadcast The tier @TIER raid on @NAME has been lost!"
    perParticipant:
      - "eco take @PLAYER 50"